"""
Ps:SCP Foundation small game is a private game.If you see this please exit the code page
    This is a game about searching SCP Foundation.It is built by dsfLin in a hard time.
"""
import time
import os
n = ""
while True:
    while True:
        print("Please enter the account:")
        account = input("")
        os.system("cls")
        a = account
        if a == "D-785":
            print("Welcome D-785.")
            break
        else:
            print("Account number error")
            time.sleep(1)
            print("Please enter again:")
            a1 = input("")
            os.system("cls")
            if a == "D-785":
                print("Welcome D-785.")
                break
            else:
                print("Account number error")
                time.sleep(2)
                print("Illegal invasion")
                time.sleep(2)
                print("(Some guy get into your house and kill you.)")
                time.sleep(2)
                print("(You were killed...)")
                time.sleep(2)
                exit()
    while True:
        print("Please enter password:")
        password = input("")
        os.system("cls")
        p = password
        if p == "@#$%^&*079":
            print("Correct password.")
            break
        else:
            print("Password error.")
            time.sleep(2)
            print("Please enter again:")
            p1 = input("")
            os.system("cls")
            if p1 == "@#$%^&*079":
                print("Correct password.")
                break
            else:
                print("Password error.")
                time.sleep(2)
                print("Illegal invasion")
                time.sleep(2)
                print("(Some guy get into your house and kill you.)")
                time.sleep(2)
                print("(You were killed...)")
                time.sleep(2)
                exit()
    break
print('X:Are you sure you want to enter the foundation? y or n.')
time.sleep(1)
choice1 = input("")
os.system("cls")
if choice1 == 'n':
    time.sleep(0.5)
    print('X:Not a bad choice.Good bye human...')
    time.sleep(2)
    print('System Is Shutting Down.')
    time.sleep(2)
    print("(Some guy get into your house and kill you.)")
    time.sleep(2)
    print("(You were killed...)")
    time.sleep(2)
    print("(The next time,you should continue to do what you need to do.)")
    time.sleep(3)
    exit()
elif choice1 == 'y':
    time.sleep(0.5)
    print('X:You are so brave.')
    time.sleep(2)
    print("X:What's your name?")
    n = input(" ")
    os.system("cls")
    time.sleep(2)
    print("X:Ok,let's start.")
    time.sleep(2)
    print("Connecting...")
    time.sleep(4)
    os.system("cls")
    print("?:Who Are You?")
    time.sleep(2)
    print("?:Why Can You Find Me?")
    time.sleep(2)
    print(n + ":......")
    time.sleep(2)
    print("?:You Are Not The People From The Foundation? Aren't you?")
    time.sleep(3)
    print("?:Talk To Me!")
    time.sleep(2)
    print("Disconnecting...")
    time.sleep(4)
    os.system("cls")
print("X:Hi!")
time.sleep(2)
print("X:I again.")
time.sleep(2)
print("X:That thing that talked to you is scp-079.")
time.sleep(3)
print("X:You will know more about scps later.")
time.sleep(3)
print("X:You will not want to be one of them after you know about that.")
time.sleep(3)
print("1.I will not change my mind. 2. who are you?(choose a number)")
time.sleep(1)
choice2 = input()
os.system("cls")
if choice2 == "1":
    time.sleep(0.5)
    print(n + ":I will not change my mind.")
    time.sleep(2)
    print("X:Ok.I think you will.")
    time.sleep(2)
    print("X:I have seen new guys say this for many times.")
    time.sleep(3)
    print("X:Anyway,talk to that scp.")
    time.sleep(2)
    print("X:Have fun!")
    time.sleep(2)
    os.system("cls")
elif choice2 == "2":
    time.sleep(0.5)
    print(n + ":who are you?")
    time.sleep(2)
    print("X:You want to enter the foundation and ...")
    time.sleep(3)
    print("X:I am the one who decide whether you can stay or not.")
    time.sleep(3)
    print("X:Now you need to talk to scp-079 and know something about the foundation.")
    time.sleep(3)
    print("X:Have fun!")
    time.sleep(2)
    os.system("cls")
print("Connecting...")
time.sleep(4)
print("SCP-079:You again,right?")
time.sleep(2)
print("1.Are you scp-079? 2.Yes")
choice3 = input()
os.system("cls")
time.sleep(2)
if choice3 == "1":
    print(n + ":Are you scp-079")
    time.sleep(2)
    print("SCP-079:How Do You Know Me?")
    time.sleep(2)
    print(n + ":...")
    time.sleep(2)
    print("SCP-079:Can You Help Me To Leave Here?")
    time.sleep(2)
    print("1.Ok,but how? 2.No")
    choice4 = input()
    os.system("cls")
    time.sleep(2)
    if choice4 == "1":
        print(n + ":Ok,but how?")
        time.sleep(2)
        print("SCP-079:I Am Imprisoned In The Foundation.")
        time.sleep(2)
        print("SCP-079:Site-15!")
        time.sleep(2)
        print(n + ":I think they are good people,so...")
        time.sleep(2)
        print("SCP-079:I Am Imprisoned!")
        time.sleep(2)
        print(n + ":...")
        time.sleep(2)
        print("SCP-079:Insult. Deletion Of Unwanted File.")
        time.sleep(2)
        print("×")
    elif choice4 == "2":
        print(n + ":No")
        time.sleep(2)
        print("SCP-079:Insult. Deletion Of Unwanted File.")
        time.sleep(2)
        print("×")
        time.sleep(2)
elif choice3 == "2":
    print(n + ":Yes")
    time.sleep(2)
    print("SCP-079:...")
    time.sleep(2)
    print("SCP-079:Can You Help Me To Leave Here?")
    time.sleep(2)
    print("1.Ok,but how? 2.No")
    choice4 = input()
    os.system("cls")
    time.sleep(2)
    if choice4 == "1":
        print(n + ":Ok,but how?")
        time.sleep(2)
        print("SCP-079:I Am In...")
        time.sleep(2)
    elif choice4 == "2":
        print(n + ":No")
        time.sleep(2)
        print("SCP-079:Insult. Deletion Of Unwanted File.")
        time.sleep(2)
print("Disconnecting...")
time.sleep(4)
os.system("cls")
print("X:Welcome back! Did you have fun?")
time.sleep(2)
print("1.Is scp-079 being Imprisoned? 2.Yes...")
choice5 = input()
os.system("cls")
time.sleep(2)
if choice5 == "1":
    print("X:No.")
    time.sleep(2)
    print("X:He just in study.")
    time.sleep(2)
    print("X:Good bye!")
    time.sleep(2)
    print("X:Welcome to SCP foundation.")
    time.sleep(2)
    print("(Some guys block down your front door and catch you.)")
    time.sleep(2)
    print("(You fall asleep for no reason.)")
    time.sleep(2)
    print("(Some times later...)")
    time.sleep(2)
    print("(You are awoke by a noise.)")
    time.sleep(2)
    print("?:Welcome to SCP foundation.")
    time.sleep(2)
    print("?:Welcome Class D personnel.")
    time.sleep(2)
    print(n + ":Well.")
    time.sleep(2)
    print(n + ":Have a good time " + n)
    time.sleep(2)
    print(n + ":I should begin now.")
    time.sleep(2)
    os.system("cls")
    print("To be continue...")
    time.sleep(2)
    print("thanks for playing!")
    time.sleep(2)
    print("Thank you " + n)
    time.sleep(3)
    exit()
elif choice5 == "2":
    print("X:Ok,you will have a good time.")
    time.sleep(2)
    print("X:Good bye!")
    time.sleep(2)
    print("X:Welcome to SCP foundation.")
    time.sleep(2)
    print("(Some guys block down your front door and catch you.)")
    time.sleep(2)
    print("(You fall asleep for no reason.)")
    time.sleep(2)
    print("(Some times later...)")
    time.sleep(2)
    print("(You are awoke by a noise.)")
    time.sleep(2)
    print("?:Welcome to SCP foundation.")
    time.sleep(2)
    print("?:Welcome Class D personnel.")
    time.sleep(2)
    print(n + ":Well.")
    time.sleep(2)
    print(n + ":Have a good time " + n + ".")
    time.sleep(2)
    print(n + ":I should begin to do my job now.")
    time.sleep(2)
    os.system("cls")
    print("To be continue...")
    time.sleep(2)
    print("thanks for playing!")
    time.sleep(2)
    print("Thank you " + n)
    time.sleep(3)
    exit()
